export const darkTheme = {
    Default:{
        background:'#121212',
        backgroundSecondary:'#1f1f1f',
        border:'#232323',
    },
    Text:{
        style:{
            color:'#fff',
        }
    },
    Icon:{
        iconStyle:{
            color:'#fff',
        },
    },
    Input:{
        style:{
            color:"#fff"
        },
    },
    Button:{
        buttonStyle:{
            backgroundColor:"#2185d0",
        },
    },
}